### ISSUE TITLE
Alternative ways of achieving the same effect

### ISSUE THREAD

**Issue by fastred** [fastred/SloppySwiper#1]
The same functionality can be obtained in one of these (less safe) ways:

1. swizzle `UIScreenEdgePanGestureRecognizer` to let it recognize pan gestures started not only from the edge (I haven't tested it yet)
2. grab the target and action from `interactivePopGestureRecognizer` and use them with `UIPanGestureRecognizer` (it uses private APIs): https://gist.github.com/fastred/3ccd1740e1464dbf8675

**Comment by SbIm** [comment]
I am also thinking about swizzle method, but I dont know the detail of interactivePopGestureRecognizer. Do u have any ideas?

**Comment by fastred** [comment]
Moved this issue to wiki: https://github.com/fastred/SloppySwiper/wiki
