### ISSUE TITLE
How to turn SloppySwiper off, and on again?

### ISSUE THREAD

**Issue by nharbo** [fastred/SloppySwiper#19]
Hi!
Thanks for SloppySwiper - it really eases my work :-) But I would like to ask, how it's possible to turn if off, and then on again? I've tried to set the navigationController's delegate to nil to turn it off, without any luck.. Is there anything buildin that i'm missing? :-)

**Comment by nharbo** [comment]
nevermind, I managed to fix it like this:
swiper.panRecognizer.requireGestureRecognizerToFail(swiper.panRecognizer)

:-)

**Comment by fastred** [comment]
Cool!

**Comment by InfiniteDreamz** [comment]
@nharbo Hey, I want the same thing in my application.

if  let temSwiper = self.navigationController?.delegate as? SloppySwiper {
            temSwiper.panRecognizer.require(toFail: temSwiper.panRecognizer)
            self.navigationController?.delegate = nil
        }
It is not working.
