### ISSUE TITLE
bug for UITabBarController.

### ISSUE THREAD

**Issue by xhzengAIB** [fastred/SloppySwiper#2]
Hi! @fastred 
Look this picture:
![slobug](https://cloud.githubusercontent.com/assets/1969908/3141300/f52b08da-e973-11e3-8a7e-8e520355b506.gif)

Jack

**Comment by fastred** [comment]
Should be fixed in https://github.com/fastred/SloppySwiper/pull/6

**Comment by yinnieryou** [comment]
I forked this repo and work out this issue.
Here is the address of my repo: https://github.com/yinnieryou/SloppySwiper
I don't know my solution is suitable for you or not, it works  perfect on my project.

![sloppyswiper](https://cloud.githubusercontent.com/assets/5241648/7876822/2cf0b5aa-0604-11e5-99ec-a42b12de7729.gif)

**Comment by techabserve** [comment]
Hi. Scrollview not working after push and back to the controller
