### ISSUE TITLE
Autorotate issue

### ISSUE THREAD

**Issue by chapaid** [fastred/SloppySwiper#9]
Was experimenting with using SloppySwiper but came across one issue when using an iPad.

If i'm on a child view controller and I change the orientation of my device then swipe back, the parent view controller does not properly readjust its layout. If I use the standard interactive popgesture though it works fine.

Let me know if I'm missing something.

**Comment by fastred** [comment]
@chapaid Thanks for reporting this. Would you be able to attach a sample project?

**Comment by joshzngf** [comment]
I'm having the same issue as well. 
The bug can be reproduced with the following steps using the sample project.
Push -> rotate screen -> swipe back -> You'll see a black part meaning the auto layout is not working
Screenshots are attached for your reference.
Thanks!

![simulator screen shot oct 22 2015 1 51 57 pm](https://cloud.githubusercontent.com/assets/1179926/10657896/1ad23f78-78c4-11e5-878c-a223d5c71ec5.png)
![simulator screen shot oct 22 2015 1 51 59 pm](https://cloud.githubusercontent.com/assets/1179926/10657897/22f15a40-78c4-11e5-850c-8078ba7c14af.png)
![simulator screen shot oct 22 2015 1 52 04 pm](https://cloud.githubusercontent.com/assets/1179926/10657899/22f6460e-78c4-11e5-9d6c-8023afe0c3f2.png)
![simulator screen shot oct 22 2015 1 52 07 pm](https://cloud.githubusercontent.com/assets/1179926/10657900/22fb8cae-78c4-11e5-94b8-3a2cf23d591f.png)
![simulator screen shot oct 22 2015 1 52 10 pm](https://cloud.githubusercontent.com/assets/1179926/10657898/22f4c55e-78c4-11e5-8eee-56d719ea45b9.png)
